name: Setup Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-setup:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run setup script
      run: |
        cd ted_consensus_1.0
        chmod +x setup.sh
        ./setup.sh

    - name: Verify stride installation
      run: |
        if [ -f "./programs/stride/stride" ]; then
          echo "Stride file exists"
        else
          echo "Stride compilation failed"
          exit 1
        fi
        ted_consensus_1.0/programs/chainsaw/stride/stride programs/chainsaw/example_files/AF-Q5T5X7-F1-model_v4.pdb -r A 
        

    - name: Run example segmentation
      run: |
        chmod +x run_segmentation.sh
        ./run_segmentation.sh -i example -o example_output

    - name: Check output
      run: |
        if [ -f "./example_output/consensus.tsv" ]; then
          echo "Segmentation completed successfully"
        else
          echo "Segmentation failed"
          exit 1
        fi